ElCaminoDeCostaRica/ElCaminoDeCostaRica/Models/Question.cs
using System.ComponentModel.DataAnnotations;
using System;


namespace ElCaminoDeCostaRica.Models
{
    public class Question
    {
<<<<<<< HEAD
=======
        public int id { get; set; }

>>>>>>> Cesar
        [Required(ErrorMessage = "Debe ingresar la encuesta")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Encuesta")]
        public int idSurvey { get; set; }

        [Required(ErrorMessage = "Debe ingresar el servicio")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Servicio")]
        public int idService { get; set; }

        [Required(ErrorMessage = "Debe ingresar la pregunta")]
        [MaxLength(1000, ErrorMessage = "No puede exceder 1000 caracteres")]
        [MinLength(1, ErrorMessage = "Debe ingresar al menos 1 caracter")]
        [Display(Name = "Pregunta")]
        public string question { get; set; }
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Controllers/QuestionController.cs
using System.Web.Mvc;
using ElCaminoDeCostaRica.Models;

namespace ElCaminoDeCostaRica.Controllers
{
    public class QuestionController : Controller
    {
        Database database = new Database();
        public ActionResult addQuestion()
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            return View();
        }

        [HttpPost]
        public ActionResult addQuestion(Question question)
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ViewBag.Success = false;
            try
            {
                if (ModelState.IsValid)
                {
                    database.openConnection();
                    ViewBag.Success = database.addQuestion(question);
                    database.closeConnection();
                    if (ViewBag.Success)
                    {
                        ViewBag.Message = "La pregunta fue creada con exito.";
                        ModelState.Clear();
                    }

                }

                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salio mal y no fue posible crear la pregunta.";
                return View();
            }

        }

        public ActionResult questionList()
        {
            database.openConnection();
            ViewBag.questions = database.questionList();
            database.closeConnection();
            return View();
        }

        [HttpGet]
        public ActionResult questionDelete(int identificador)
        {
            ViewBag.ExitoAlBorrar = false;
            database.openConnection();
            database.questionDelete(identificador);
            database.closeConnection();
<<<<<<< HEAD
=======
            database.openConnection();
            ViewBag.questions=database.questionList();
            database.closeConnection();
>>>>>>> Cesar
            return View("questionList");
        }

        [HttpGet]
        public ActionResult questionEdit(int? identificador)
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ActionResult vista;
            try
            {
                database.openConnection();
<<<<<<< HEAD
                Question questionItem = database.questionList().Find(smodel => smodel.idSurvey == identificador);
=======
                Question questionItem = database.questionList().Find(smodel => smodel.id == identificador);
>>>>>>> Cesar
                database.closeConnection();
                if (questionItem == null)
                {
                    vista = RedirectToAction("questionList");
                }
                else
                {
                    vista = View(questionItem);
                }
            }
            catch
            {
                vista = RedirectToAction("questionList");
            }
            return vista;
        }

        [HttpPost]
        public ActionResult questionEdit(Question question)
        {
            try
            {
                database.openConnection();
                database.questionEdit(question);
                database.closeConnection();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Question/addQuestion.cshtml
@model ElCaminoDeCostaRica.Models.Question
@{
    List<SelectListItem> surveys = new List<SelectListItem>();
    List<SelectListItem> services = new List<SelectListItem>();
    foreach (var survey in ViewBag.Surveys)
    {
        surveys.Add(
        new SelectListItem { Text = Convert.ToString(survey.id), Value = Convert.ToString(survey.id) }
        );
    }

    foreach (var service in ViewBag.Services)
    {
        services.Add(
        new SelectListItem { Text = Convert.ToString(service.name), Value = Convert.ToString(service.id) }
        );
    }
}
<html>
<head>
</head>
<body class="body_Index">
<<<<<<< HEAD
=======


>>>>>>> Cesar
    @if (ViewBag.Message != null)
    {
        if (ViewBag.Success)
        {
            <div class="alert-success">
                <h3> @ViewBag.Message </h3>
            </div>
        }
        else
        {
            <div class="alert-danger">
                <h3> @ViewBag.Message </h3>
            </div>
        }
    }

    @using (Html.BeginForm("addQuestion", "Question", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
<<<<<<< HEAD
        <h1 class="formTitle">Crear pregunta</h1>
        <div class="form-horizontal">

            <div class="form-group">
                @Html.LabelFor(model => model.idSurvey, new { @class = "formLabel" })
                @Html.DropDownListFor(model => model.idSurvey, surveys, "-Sin selección - ", new { @class = "form - control" })
                @Html.ValidationMessageFor(model => model.idSurvey, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.idService, new { @class = "formLabel" })
                @Html.DropDownListFor(model => model.idService, services, "-Sin selección - ", new { @class = "form - control" })
                @Html.ValidationMessageFor(model => model.idService, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.question, new { @class = "formLabel" })
                @Html.TextBoxFor(model => model.question, new { @class = "formcontrol, formInput" })
                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
            </div>

        </div>
        <div>

            <input type="submit" class="btn btn-success btnCreate" value="Crear" />
        </div>
=======

        <section class="min-vh-100 " style=" font-size:x-large;">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col col-xl-10">
                        <div class="card" style="border-radius: 4rem; border-style: solid; border-color: #FAD586;">
                            <div class="row g-0 mb-7">

                                <div class="col-md-6 col-lg-5 d-none d-md-block" ;>
                                    <img src="https://cdn-icons-png.flaticon.com/512/121/121703.png"
                                         alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin: 8px 14px" />
                                </div>

                                <div class="col-md-6 col-lg-7 d-flex align-items-center" style="font-size:x-large">
                                    <div class="card-body p-4 p-lg-5 text-black">


                                        <form>

                                            <h1 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px; color: #184D47">Añadir Pregunta</h1>


                                            <div class="form-outline mb-4">
                                                @Html.LabelFor(model => model.idSurvey, new { @class = "formLabel" })
                                                @Html.DropDownListFor(model => model.idSurvey, surveys, "-Sin selección - ", new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.idSurvey, "", new { @class = "text-danger" })
                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example27">Apellido </label>
                                                @Html.LabelFor(model => model.idService, new { @class = "formLabel" })
                                                @Html.DropDownListFor(model => model.idService, services, "-Sin selección - ", new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.idService, "", new { @class = "text-danger" })

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example27">Email </label>
                                                @Html.LabelFor(model => model.question, new { @class = "formLabel" })
                                                @Html.TextBoxFor(model => model.question, new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
                                            </div>

                                            <div class="pt-1 mb-4">
                                                <a href="~/Views/Home/Index.cshtml">
                                                    <input type="submit" class="rounded-3 btnLogin"
                                                           style=" margin: 10px; background-color: #FAD586; color:black; "
                                                           value="Guardar Cambios" />
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

>>>>>>> Cesar
    }
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Question/questionEdit.cshtml
@model ElCaminoDeCostaRica.Models.Question
@{
    List<SelectListItem> surveys = new List<SelectListItem>();
    List<SelectListItem> services = new List<SelectListItem>();
    foreach (var survey in ViewBag.Surveys)
    {
        surveys.Add(
        new SelectListItem { Text = Convert.ToString(survey.id), Value = Convert.ToString(survey.id) }
        );
    }

    foreach (var service in ViewBag.Services)
    {
        services.Add(
        new SelectListItem { Text = Convert.ToString(service.name), Value = Convert.ToString(service.id) }
        );
    }
}

<html>
<head>
</head>
<body>
    @using (Html.BeginForm("questionEdit", "Question", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
<<<<<<< HEAD
@Html.AntiForgeryToken()
                <h1>Formulario de edicion de pregunta</h1>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.idSurvey, new { @class = "formLabel" })
                                    @Html.DropDownListFor(model => model.idSurvey, surveys, "-Sin selección - ", new { @class = "form - control" })
                                    @Html.ValidationMessageFor(model => model.idSurvey, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.idService, new { @class = "formLabel" })
                                    @Html.DropDownListFor(model => model.idService, services, "-Sin selección - ", new { @class = "form - control" })
                                    @Html.ValidationMessageFor(model => model.idService, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.question, new { @class = "formLabel" })
                                    @Html.TextBoxFor(model => model.question, new { @class = "formcontrol, formInput" })
                                    @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
                                </div>
                                            </body>}
=======
        @Html.AntiForgeryToken()


        <section class="min-vh-100 " style=" font-size:x-large;">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col col-xl-10">
                        <div class="card" style="border-radius: 4rem; border-style: solid; border-color: #FAD586;">
                            <div class="row g-0 mb-7">

                                <div class="col-md-6 col-lg-5 d-none d-md-block" ;>
                                    <img src="https://cdn-icons-png.flaticon.com/512/121/121703.png"
                                         alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin: 8px 14px" />
                                </div>

                                <div class="col-md-6 col-lg-7 d-flex align-items-center" style="font-size:x-large">
                                    <div class="card-body p-4 p-lg-5 text-black">


                                        <form>

                                            <h1 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px; color: #184D47">Modificar Pregunta</h1>



                                            <div class="form-outline mb-4">
                                                @Html.LabelFor(model => model.idSurvey, new { @class = "formLabel" })
                                                @Html.DropDownListFor(model => model.idSurvey, surveys, "-Sin selección - ", new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.idSurvey, "", new { @class = "text-danger" })
                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example27">Apellido </label>
                                                @Html.LabelFor(model => model.idService, new { @class = "formLabel" })
                                                @Html.DropDownListFor(model => model.idService, services, "-Sin selección - ", new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.idService, "", new { @class = "text-danger" })

                                            </div>

                                            <div class="form-outline mb-4">
                                                <label class="form-label" for="form2Example27">Email </label>
                                                @Html.LabelFor(model => model.question, new { @class = "formLabel" })
                                                @Html.TextBoxFor(model => model.question, new { @class = "form-control,form-control-lg" })
                                                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })

                                            </div>

                                            <div class="pt-1 mb-4">
                                                <a href="~/Views/Home/Index.cshtml">
                                                    <input type="submit" class="rounded-3 btnLogin"
                                                           style=" margin: 10px; background-color: #FAD586; color:black; "
                                                           value="Guardar Cambios" />
                                                </a>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

    }
    </body>
>>>>>>> Cesar
    @section Scripts
{
        @Scripts.Render("~/bundles/jqueryval")
    }
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Question/questionList.cshtml
@model ElCaminoDeCostaRica.Models.Question
@{ ViewBag.Title = "Preguntas"; }
<html>
<head>
</head>

<body class="body_Form">

<<<<<<< HEAD
    <h1 align="center" style="color:black; font-family:Agrozza Demo">Lista de preguntas</h1>
    <div class="seccion_1" id="s1">
        <table class="table">
            <tr>
                <th class="text-center">Encuesta</th>
                <th class="text-center">Servicio</th>
                <th class="text-center">Pregunta</th>

=======
    <div class="table-responsive m-lg-2">
        <table class="table">
            <h1 align="center" style="color: #184D47; font-family: Agrozza Demo">Lista de Preguntas</h1>
            <tr style="color: #184D47">
                <th scope="col" class="text-center">Identificación</th>
                <th scope="col" class="text-center">Nombre</th>
                <th scope="col" class="text-center">Apellido</th>
                <th scope="col" class="text-center">Email</th>
                <th scope="col" class="text-center">Tipo</th>
                <th scope="col" class="text-center">Teléfono</th>
>>>>>>> Cesar
            </tr>
            <tbody>
                @foreach (var question in ViewBag.questions)
                {
                    <tr>
<<<<<<< HEAD
                        <td class="text-center"> @question.idSurvey </td>
                        <td class="text-center"> @question.idService </td>
                        <td class="text-center"> @question.question </td>

                        <td>
                            @Html.ActionLink("Modificar", "", new { },
                                      new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere modificar esta pregunta ? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Borrar", "questionkDelete", new { identificador = question.idSurvey },
                                  new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere borrar esta pregunta? ');" })
=======
                        <td scope="row" class="text-center"> @question.idSurvey </td>
                        <td scope="row" class="text-center"> @question.idService </td>
                        <td scope="row" class="text-center"> @question.question </td>

                        <td>
                            @Html.ActionLink("Modificar", "", new { },
                                      new { @class = "btnLogin alert-info", @onclick = "return confirm('¿Quiere modificar esta pregunta ? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Borrar", "questionDelete", new { identificador = question.idSurvey },
                                  new { @class = "btnLogin alert-info", @onclick = "return confirm('¿Quiere borrar esta pregunta? ');" })
>>>>>>> Cesar
                        </td>
                    </tr>
                }
            </tbody>
        </table>
<<<<<<< HEAD
    </div>
=======




>>>>>>> Cesar
</body>
</html>