ElCaminoDeCostaRica/ElCaminoDeCostaRica/Models/Stage.cs
using System.ComponentModel.DataAnnotations;
using System;

namespace ElCaminoDeCostaRica.Models
{
    public class Stage
    {
        public int id { get; set; }

<<<<<<< HEAD
=======
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe ingresar el nombre")]
        [MaxLength(250, ErrorMessage = "No puede exceder 250 caracteres")]
        [MinLength(1, ErrorMessage = "Debe ingresar al menos 1 caracter")]
        public string name { get; set; }

>>>>>>> Cesar
        [Required(ErrorMessage = "Debe ingresar el inicio")]
        [MaxLength(250, ErrorMessage = "No puede exceder 250 caracteres")]
        [MinLength(1, ErrorMessage = "Debe ingresar al menos 1 caracter")]
        [Display(Name = "Inicio")]
        public string start { get; set; }

        [Required(ErrorMessage = "Debe ingresar el final")]
        [MaxLength(250, ErrorMessage = "No puede exceder 250 caracteres")]
        [MinLength(1, ErrorMessage = "Debe ingresar al menos 1 caracter")]
        [Display(Name = "Final")]
        public string finish { get; set; }

        [Required(ErrorMessage = "Debe ingresar la distancia")]
        [Range(float.MinValue, float.MaxValue)]
        [Display(Name = "Distancia en KM")]
        public float distance { get; set; }

        [Required(ErrorMessage = "Debe ingresar la altimetria minima")]
        [Range(float.MinValue, float.MaxValue)]
        [Display(Name = "Altimetria minima")]
        public float minAltimetry { get; set; }

        [Required(ErrorMessage = "Debe ingresar la altimetria maxima")]
        [Range(float.MinValue, float.MaxValue)]
        [Display(Name = "Altimetria maxima")]
        public float maxAltimetry { get; set; }

        [Required(ErrorMessage = "Debe ingresar la ruta")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Ruta")]
        public int idRoute { get; set; }
<<<<<<< HEAD
=======

        [Required(ErrorMessage = "Debe ingresar la seccion")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Seccion")]
        public int idSection { get; set; }
>>>>>>> Cesar
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Controllers/StageController.cs
using ElCaminoDeCostaRica.Models;
<<<<<<< HEAD
=======
using System;
>>>>>>> Cesar
using System.Web.Mvc;

namespace ElCaminoDeCostaRica.Controllers
{
    public class StageController : Controller
    {
        Database database = new Database();
        public ActionResult addStage()
        {
            database.openConnection();
            ViewBag.Data = database.routeList();
            database.closeConnection();

            return View();
        }

        [HttpPost]
        public ActionResult addStage(Stage stage)
        {
            database.openConnection();
            ViewBag.Data = database.routeList();
            database.closeConnection();

            ViewBag.Success = false;
            try
            {
                if (ModelState.IsValid)
                {
                    database.openConnection();
                    ViewBag.Success = database.addStage(stage);
                    database.closeConnection();
                    if (ViewBag.Success)
                    {
                        ViewBag.Message = "La etapa " + stage.id + " fue creada con exito.";
                        ModelState.Clear();
                    }

                }

                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salio mal y no fue posible crear la etapa.";
                return View();
            }

        }

        public ActionResult stageList()
        {
            database.openConnection();
            ViewBag.stages = database.stageList();
            database.closeConnection();
            return View();
        }

        [HttpGet]
        public ActionResult stageDelete(int identificador)
        {
            ViewBag.ExitoAlBorrar = false;
            database.openConnection();
            database.stageDelete(identificador);
            ViewBag.stages = database.stageList();
            database.closeConnection();
            return View("stageList");
        }

        [HttpGet]
        public ActionResult stageEdit(int? identificador)
        {
            database.openConnection();
            ViewBag.Data = database.routeList();
            database.closeConnection();
            ActionResult vista;
            try
            {
                database.openConnection();
                Stage stageItem = database.stageList().Find(smodel => smodel.id == identificador);
                database.closeConnection();
                if (stageItem == null)
                {
                    vista = RedirectToAction("stageList");
                }
                else
                {
                    vista = View(stageItem);
                }
            }
            catch
            {
                vista = RedirectToAction("stageList");
            }
            return vista;
        }

        [HttpPost]
        public ActionResult stageEdit(Stage stage)
        {
            try
            {
                database.openConnection();
                database.stageEdit(stage);
<<<<<<< HEAD
                database.closeConnection();
                return RedirectToAction("Index", "Home");
=======
                ViewBag.stages = database.stageList();
                database.closeConnection();
                return RedirectToAction("stageList");
>>>>>>> Cesar
            }
            catch
            {
                return View();
            }
        }
<<<<<<< HEAD
=======

        public ActionResult Inscription(int? identificador)
        {
            bool addInscription = true;
            Inscription newInscription = new Inscription { idUser = 123456, idStage = Convert.ToInt32(identificador) };
            database.openConnection();
            ViewBag.inscriptions = database.inscriptionList();
            database.closeConnection();
            foreach (var inscription in ViewBag.inscriptions)
            {
                if (inscription.idUser == newInscription.idUser && inscription.idStage== newInscription.idStage) 
                {
                    ViewBag.Message = "Algo salio mal y no fue posible inscribirse.";
                    
                    addInscription = false;
                }
            }
            if (addInscription)
            {
                database.openConnection();
                ViewBag.Data = database.inscription(newInscription);
                database.closeConnection();
            }   
            database.openConnection();
            ViewBag.stages = database.stageList();
            database.closeConnection();
            return View("stageList");
        }
>>>>>>> Cesar
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Stage/addStage.cshtml
@model ElCaminoDeCostaRica.Models.Stage
@{
    List<SelectListItem> routes = new List<SelectListItem>();
    foreach (var route in ViewBag.Data)
    {
        routes.Add(
        new SelectListItem { Text = Convert.ToString(route.id), Value = Convert.ToString(route.id) }
        );
    } }

<html>
<head>
<<<<<<< HEAD
    
</head>
<body>
    <div class="container_Green formTitleCenter">
=======

</head>
<body>
    <div>
>>>>>>> Cesar
        @if (ViewBag.Resultado != null)
        {
            <div class="alert-success">
                <h3> @ViewBag.Message </h3>
            </div>
        }
        @if (ViewBag.Message != null)
        {
            if (ViewBag.Success)
            {
                <div class="alert-success">
                    <h3> @ViewBag.Message </h3>
                </div>
            }
            else
            {
                <div class="alert-danger">
                    <h3> @ViewBag.Message </h3>
                </div>
            }
        }

        <div id="map"></div>

        @using (Html.BeginForm("addStage", "Stage", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
<<<<<<< HEAD
            <h1 class="formTitle" style="text-align:center">Crear etapa</h1>
            <div class="form-horizontal">

                <div class="form-group">
                    @Html.LabelFor(model => model.start, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.start, new { @class = "form-control, formInput" })
                    @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.finish, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.finish, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.finish, "", new { @class = "text-danger" })
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.distance, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.distance, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.minAltimetry, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.minAltimetry, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.minAltimetry, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.maxAltimetry, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.maxAltimetry, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.maxAltimetry, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.idRoute, new { @class = "formLabel" })
                    @Html.DropDownListFor(model => model.idRoute, routes, "-Sin selección - ", new { @class = "form - control" })
                    @Html.ValidationMessageFor(model => model.idRoute, "", new { @class = "text-danger" })
                </div>
            </div>

            <div>

                <input id="submitButton" type="submit" class="btn btn-success btnCreate" value="Crear" />
            </div>
=======



            <section class="min-vh-100 " style=" font-size:x-large;">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col col-xl-10">
                            <div class="card" style="border-radius: 4rem; border-style: solid; border-color: #FAD586;">
                                <div class="row g-0 mb-7">

                                    <div class="col-md-6 col-lg-5 d-none d-md-block" ;>
                                        <img src="https://cdn-icons-png.flaticon.com/512/4252/4252489.png"
                                             alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin: 8px 14px" />
                                    </div>

                                    <div class="col-md-6 col-lg-7 d-flex align-items-center" style="font-size:x-large">
                                        <div class="card-body p-4 p-lg-5 text-black">
                                            @Html.HiddenFor(model => model.id)

                                            <form>

                                                <h1 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px; color: #184D47">Agregar  Etapa</h1>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.start, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.start, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
                                                    </div>
                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.finish, new { @class = "formLabel" })
                                                        @Html.TextBoxFor(model => model.finish, new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.finish, "", new { @class = "text-danger" })
                                                    </div>

                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.distance, new { @class = "formLabel" })
                                                        @Html.TextBoxFor(model => model.distance, new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
                                                    </div>

                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.minAltimetry, new { @class = "formLabel" })
                                                        @Html.TextBoxFor(model => model.minAltimetry, new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.minAltimetry, "", new { @class = "text-danger" })
                                                    </div>

                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.maxAltimetry, new { @class = "formLabel" })
                                                        @Html.TextBoxFor(model => model.maxAltimetry, new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.maxAltimetry, "", new { @class = "text-danger" })
                                                    </div>

                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.idRoute, new { @class = "formLabel" })
                                                        @Html.DropDownListFor(model => model.idRoute, routes, "-Sin selección - ", new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.idRoute, "", new { @class = "text-danger" })
                                                    </div>

                                                    <div class="pt-1 mb-4">
                                                        <a href="~/Views/Home/Index.cshtml">
                                                            <input type="submit" class="rounded-3 btnLogin"
                                                                   style=" margin: 10px; background-color: #FAD586; color:black; "
                                                                   value="Guardar Cambios" />
                                                        </a>
                                                    </div>


                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>



>>>>>>> Cesar

        }
    </div>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Stage/stageEdit.cshtml
@model ElCaminoDeCostaRica.Models.Stage
<<<<<<< HEAD
@{ 
=======
@{
>>>>>>> Cesar
    List<SelectListItem> routes = new List<SelectListItem>();
    foreach (var route in ViewBag.Data)
    {
        routes.Add(
        new SelectListItem { Text = Convert.ToString(route.id), Value = Convert.ToString(route.id) }
        );
    } }
<<<<<<< HEAD
  
=======

>>>>>>> Cesar
<html>
<head>
</head>
<body>
<<<<<<< HEAD
    <div class="container_Rose formTitleCenter">
=======
    <div>
>>>>>>> Cesar
        @using (Html.BeginForm("stageEdit", "Stage", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            @Html.AntiForgeryToken()
<<<<<<< HEAD
            <h1>Formulario de edicion de etapa</h1>
            <div class="form-horizontal">
                @Html.HiddenFor(model => model.id)

                <div class="form-group">
                    @Html.LabelFor(model => model.start, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.start, new { @class = "form-control, formInput" })
                    @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.finish, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.finish, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.finish, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.distance, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.distance, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.minAltimetry, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.minAltimetry, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.minAltimetry, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.maxAltimetry, new { @class = "formLabel" })
                    @Html.TextBoxFor(model => model.maxAltimetry, new { @class = "formcontrol, formInput" })
                    @Html.ValidationMessageFor(model => model.maxAltimetry, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.idRoute, new { @class = "formLabel" })
                    @Html.DropDownListFor(model => model.idRoute, routes, "-Sin selección - ", new { @class = "form - control" })
                    @Html.ValidationMessageFor(model => model.idRoute, "", new { @class = "text-danger" })
                </div>

                <div>
                    <input type="submit" class="btn btn-success" value="Aplicar cambios" />
                </div>
            </div>
=======


            <section class="min-vh-100 " style=" font-size:x-large;">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col col-xl-10">
                            <div class="card" style="border-radius: 4rem; border-style: solid; border-color: #FAD586;">
                                <div class="row g-0 mb-7">

                                    <div class="col-md-6 col-lg-5 d-none d-md-block" ;>
                                        <img src="https://cdn-icons-png.flaticon.com/512/4252/4252489.png"
                                             alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin: 8px 14px" />
                                    </div>

                                    <div class="col-md-6 col-lg-7 d-flex align-items-center" style="font-size:x-large">
                                        <div class="card-body p-4 p-lg-5 text-black">
                                            @Html.HiddenFor(model => model.id)

                                            <form>

                                                <h1 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px; color: #184D47">Modificar Etapa</h1>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.start, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.start, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.start, "", new { @class = "text-danger" })
                                                </div>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.finish, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.finish, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.finish, "", new { @class = "text-danger" })
                                                </div>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.distance, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.distance, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.distance, "", new { @class = "text-danger" })
                                                </div>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.minAltimetry, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.minAltimetry, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.minAltimetry, "", new { @class = "text-danger" })
                                                </div>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.maxAltimetry, new { @class = "formLabel" })
                                                    @Html.TextBoxFor(model => model.maxAltimetry, new { @class = "form-control, form-Input-control" })
                                                    @Html.ValidationMessageFor(model => model.maxAltimetry, "", new { @class = "text-danger" })

                                                    <div class="form-outline mb-4">
                                                        @Html.LabelFor(model => model.idRoute, new { @class = "formLabel" })
                                                        @Html.DropDownListFor(model => model.idRoute, routes, "-Sin selección - ", new { @class = "form-control, form-Input-control" })
                                                        @Html.ValidationMessageFor(model => model.idRoute, "", new { @class = "text-danger" })
                                                    </div>


                                                    <div class="pt-1 mb-4">
                                                        <a href="~/Views/Home/Index.cshtml">
                                                            <input type="submit" class="rounded-3 btnLogin"
                                                                   style=" margin: 10px; background-color: #FAD586; color:black; "
                                                                   value="Guardar Cambios" />
                                                        </a>
                                                    </div>


                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

>>>>>>> Cesar
        }
    </div>
</body>
@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Stage/stageList.cshtml
@model ElCaminoDeCostaRica.Models.Stage
@{ ViewBag.Title = "Etapas"; }
<html>
<head>
</head>

<body>
<<<<<<< HEAD
    <div class="container_Green">
        <h1 align="center" style="color:black; font-family:Agrozza Demo">Lista de etapas</h1>
        <div class="seccion_1" id="s1">
            <table class="table">
                <tr>
                    <th class="text-center">Id</th>
                    <th class="text-center">Inicio</th>
                    <th class="text-center">Final</th>
                    <th class="text-center">Distancia en KM</th>
                    <th class="text-center">Altimetria minima MSNM</th>
                    <th class="text-center">Altimetria maxima MSNM</th>
                    <th class="text-center">Ruta</th>

                </tr>
                <tbody>
                    @foreach (var stage in ViewBag.stages)
                    {
                        <tr>
                            <td class="text-center"> @stage.id </td>
                            <td class="text-center"> @stage.start </td>
                            <td class="text-center"> @stage.finish </td>
                            <td class="text-center"> @stage.distance </td>
                            <td class="text-center"> @stage.minAltimetry </td>
                            <td class="text-center"> @stage.maxAltimetry </td>
                            <td class="text-center"> @stage.idRoute </td>

                            <td>
                                @Html.ActionLink("Modificar", "stageEdit", new { identificador = stage.id },
                                          new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere modificar esta etapa ? ');" })
                            </td>
                            <td>
                                @Html.ActionLink("Borrar", "stageDelete", new { identificador = stage.id },
                                      new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere borrar esta etapa? ');" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
=======


    <div class="table-responsive m-lg-2">
        <h1 align="center" style="color: #184D47; font-family: Agrozza Demo">Lista de Etapas</h1>
        <table class="table">
            <tr style="color: #184D47">
                <th scope="col" class="text-center">Id</th>
                <th scope="col" class="text-center">Inicio</th>
                <th scope="col" class="text-center">Final</th>
                <th scope="col" class="text-center">Distancia en KM</th>
                <th scope="col" class="text-center">Altimetria minima MSNM</th>
                <th scope="col" class="text-center">Altimetria maxima MSNM</th>
                <th scope="col" class="text-center">Ruta</th>
            </tr>
            <tbody>
                @foreach (var stage in ViewBag.stages)
                {
                    <tr>
                        <td scope="row" class="text-center"> @stage.id </td>
                        <td scope="row" class="text-center"> @stage.start </td>
                        <td scope="row" class="text-center"> @stage.finish </td>
                        <td scope="row" class="text-center"> @stage.distance </td>
                        <td scope="row" class="text-center"> @stage.minAltimetry </td>
                        <td scope="row" class="text-center"> @stage.maxAltimetry </td>
                        <td scope="row" class="text-center"> @stage.idRoute </td>

                        <td>
                            @Html.ActionLink("Modificar", "stageEdit", new { identificador = stage.id },
                                      new { @class = "btnLogin alert-info", @onclick = "return confirm('¿Quiere modificar esta etapa ? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Borrar", "stageDelete", new { identificador = stage.id },
                                  new { @class = "btnLogin alert-info", @onclick = "return confirm('¿Quiere borrar esta etapa? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Inscribirse", "Inscription", new { identificador = stage.id },
                                  new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere inscribirse en esta etapa? '};" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>



    </div>

>>>>>>> Cesar
</body>
</html>