ElCaminoDeCostaRica/ElCaminoDeCostaRica/Models/Question.cs
using System.ComponentModel.DataAnnotations;
using System;


namespace ElCaminoDeCostaRica.Models
{
    public class Question
    {
<<<<<<< HEAD
=======
        public int id { get; set; }

>>>>>>> Cesar
        [Required(ErrorMessage = "Debe ingresar la encuesta")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Encuesta")]
        public int idSurvey { get; set; }

        [Required(ErrorMessage = "Debe ingresar el servicio")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Servicio")]
        public int idService { get; set; }

        [Required(ErrorMessage = "Debe ingresar la pregunta")]
        [MaxLength(1000, ErrorMessage = "No puede exceder 1000 caracteres")]
        [MinLength(1, ErrorMessage = "Debe ingresar al menos 1 caracter")]
        [Display(Name = "Pregunta")]
        public string question { get; set; }
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Models/Survey.cs
using System.ComponentModel.DataAnnotations;
using System;


namespace ElCaminoDeCostaRica.Models
{
    public class Survey
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Debe ingresar la version")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Version")]
        public int version { get; set; }

<<<<<<< HEAD
        [Required(ErrorMessage = "Debe ingresar fecha y formato de fecha valida: yyyy-mm-dd")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime day { get; set; }


=======
>>>>>>> Cesar
        [Required(ErrorMessage = "Debe ingresar la categoria")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Categoria")]
        public int idCategory { get; set; }

        [Required(ErrorMessage = "Debe ingresar el servicio")]
        [Range(int.MinValue, int.MaxValue)]
        [Display(Name = "Servicio")]
        public int idService { get; set; }

    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Controllers/QuestionController.cs
using System.Web.Mvc;
using ElCaminoDeCostaRica.Models;

namespace ElCaminoDeCostaRica.Controllers
{
    public class QuestionController : Controller
    {
        Database database = new Database();
        public ActionResult addQuestion()
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            return View();
        }

        [HttpPost]
        public ActionResult addQuestion(Question question)
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ViewBag.Success = false;
            try
            {
                if (ModelState.IsValid)
                {
                    database.openConnection();
                    ViewBag.Success = database.addQuestion(question);
                    database.closeConnection();
                    if (ViewBag.Success)
                    {
                        ViewBag.Message = "La pregunta fue creada con exito.";
                        ModelState.Clear();
                    }

                }

                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salio mal y no fue posible crear la pregunta.";
                return View();
            }

        }

        public ActionResult questionList()
        {
            database.openConnection();
            ViewBag.questions = database.questionList();
            database.closeConnection();
            return View();
        }

        [HttpGet]
        public ActionResult questionDelete(int identificador)
        {
            ViewBag.ExitoAlBorrar = false;
            database.openConnection();
            database.questionDelete(identificador);
            database.closeConnection();
<<<<<<< HEAD
=======
            database.openConnection();
            ViewBag.questions=database.questionList();
            database.closeConnection();
>>>>>>> Cesar
            return View("questionList");
        }

        [HttpGet]
        public ActionResult questionEdit(int? identificador)
        {
            database.openConnection();
            ViewBag.Surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ActionResult vista;
            try
            {
                database.openConnection();
<<<<<<< HEAD
                Question questionItem = database.questionList().Find(smodel => smodel.idSurvey == identificador);
=======
                Question questionItem = database.questionList().Find(smodel => smodel.id == identificador);
>>>>>>> Cesar
                database.closeConnection();
                if (questionItem == null)
                {
                    vista = RedirectToAction("questionList");
                }
                else
                {
                    vista = View(questionItem);
                }
            }
            catch
            {
                vista = RedirectToAction("questionList");
            }
            return vista;
        }

        [HttpPost]
        public ActionResult questionEdit(Question question)
        {
            try
            {
                database.openConnection();
                database.questionEdit(question);
                database.closeConnection();
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
    }
}

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Controllers/SurveyController.cs
using ElCaminoDeCostaRica.Models;
using System.Web.Mvc;
using System.Collections.Generic;
<<<<<<< HEAD
=======
using System;
>>>>>>> Cesar

namespace ElCaminoDeCostaRica.Controllers
{
    public class SurveyController : Controller
    {
        Database database = new Database();
        public ActionResult addSurvey()
        {
            database.openConnection();
            ViewBag.Categories = database.categoryList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            return View();
        }

        [HttpPost]
        public ActionResult addSurvey(Survey survey, FormCollection form)
        {
            database.openConnection();
            ViewBag.Categories = database.categoryList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ViewBag.Success = false;
            try
            {
                if (ModelState.IsValid)
                {
                    database.openConnection();
                    bool surveyAdded = database.addSurvey(survey);
                    database.closeConnection();
<<<<<<< HEAD
                    
                    if (surveyAdded)
                    {
                        database.openConnection();
                        survey.id = database.getSurveyID(survey.day);
=======

                    if (surveyAdded)
                    {
                        database.openConnection();
                        survey.id = database.getSurveyID(survey);
>>>>>>> Cesar
                        database.closeConnection();
                        for (int index = 1; index < 6; ++index)
                        {
                            var question = form["numero" + index];
                            if (!string.IsNullOrEmpty(question.ToString()))
                            {
                                Question questions = new Question { idSurvey = survey.id, idService = survey.idService, question = question };
                                database.openConnection();
                                ViewBag.Success = database.addQuestion(questions);
                                database.closeConnection();
                            }
                        }
                    }
                }
                if (ViewBag.Success)
                {
                    ViewBag.Message = "La encuesta " + survey.id + " fue creada con exito.";
                    ModelState.Clear();
                }
                return View();
            }
            catch
            {
                ViewBag.Message = "Algo salio mal y no fue posible crear la encuesta.";
                return View();
            }
        }

        public ActionResult surveyList()
        {
            database.openConnection();
            ViewBag.surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.cat = database.categoryList();
            database.closeConnection();
            database.openConnection();
            ViewBag.ser = database.serviceList();
            database.closeConnection();
            return View();
        }

        [HttpGet]
        public ActionResult surveyDelete(int identificador)
        {
            ViewBag.ExitoAlBorrar = false;
            database.openConnection();
            database.surveyDelete(identificador);
<<<<<<< HEAD
            ViewBag.surveys = database.surveyList();
            database.closeConnection();
=======
            database.closeConnection();
            database.openConnection();
            ViewBag.surveys = database.surveyList();
            database.closeConnection();
            database.openConnection();
            ViewBag.cat = database.categoryList();
            database.closeConnection();
            database.openConnection();
            ViewBag.ser = database.serviceList();
            database.closeConnection();
>>>>>>> Cesar
            return View("surveyList");
        }

        [HttpGet]
<<<<<<< HEAD
        public ActionResult surveyEdit(int? identificador)
=======
        public ActionResult surveyEdit(int? identificador, FormCollection form)
>>>>>>> Cesar
        {
            database.openConnection();
            ViewBag.Categories = database.categoryList();
            database.closeConnection();
            database.openConnection();
            ViewBag.Services = database.serviceList();
            database.closeConnection();
            ActionResult vista;
            try
            {
                database.openConnection();
                Survey surveyItem = database.surveyList().Find(smodel => smodel.id == identificador);
                database.closeConnection();
<<<<<<< HEAD
                Survey newSurvey = new Survey { version = surveyItem.version + 1, idCategory = surveyItem.idCategory, idService = surveyItem.idService, day = surveyItem.day };
=======
                database.openConnection();
                ViewBag.questions = database.questionList();
                database.closeConnection();
                Question item = new Question();
                List<Question> questions = new List<Question>();
                foreach (var question in ViewBag.questions)
                {
                    if (question.idSurvey == surveyItem.id)
                    {
                        questions.Add(question);
                    }
                }
                //database.openConnection();
                //Question questionItem = database.questionList().Find(smodel => smodel.idSurvey == identificador);
                //database.closeConnection();
                Survey newSurvey = new Survey { version = surveyItem.version + 1, idCategory = surveyItem.idCategory, idService = surveyItem.idService };
   
>>>>>>> Cesar
                database.openConnection();
                database.addSurvey(newSurvey);
                database.closeConnection();
                if (surveyItem == null)
                {

                    vista = RedirectToAction("surveyList");
                }
                else
                {
<<<<<<< HEAD
                    vista = View(surveyItem);
=======
                    var tuple = new Tuple<Survey, List<Question>>(surveyItem, questions);
                    vista = View(tuple);
>>>>>>> Cesar
                }
            }
            catch
            {
                vista = RedirectToAction("surveyList");
            }
            return vista;
        }

        [HttpPost]
<<<<<<< HEAD
        public ActionResult surveyEdit(Survey survey)
        {
            try
            {
                database.openConnection();
                database.surveyEdit(survey);
                database.closeConnection();
=======
        public ActionResult surveyEdit(FormCollection form)
        {
            //System.Diagnostics.Debug.WriteLine(form["Item2[1].question"]);
            Survey newSurvey = new Survey
            {
                id = Convert.ToInt32(form["Item1.id"]),
                version = Convert.ToInt32(form["Item1.version"]),
                idCategory = Convert.ToInt32(form["Item1.idCategory"]),
                idService = Convert.ToInt32(form["Item1.idService"])

            };

            try
            {
                database.openConnection();
                ViewBag.Categories = database.categoryList();
                database.closeConnection();
                database.openConnection();
                ViewBag.Services = database.serviceList();
                database.closeConnection();
                database.openConnection();
                database.surveyEdit(newSurvey);
                database.closeConnection();
                database.openConnection();
                ViewBag.questions = database.questionList();
                database.closeConnection();
                List<Question> questions = new List<Question>();
                for (int i = 0; i < ViewBag.questions.Count; i++)
                {
                    Question question = new Question
                    {
                       id = Convert.ToInt32(form["Item2[" + i + "].id"] +1 ),
                        idSurvey = newSurvey.id,
                        idService = newSurvey.idService,
                        question = form["Item2[" + i + "].question"]
                    };
                    System.Diagnostics.Debug.WriteLine(form["Item2[" + i + "].question"]);
                    database.openConnection();
                    database.questionEdit(question);
                    database.closeConnection();
                }

>>>>>>> Cesar
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }
<<<<<<< HEAD
=======

        [HttpGet]
        public ActionResult Questions(int? identificador)
        {

            /*  database.openConnection();
              ViewBag.cat = database.categoryList();
              database.closeConnection();
              database.openConnection();
              ViewBag.ser = database.serviceList();
              database.closeConnection();*/
            ActionResult vista;
            try
            {
                database.openConnection();
                ViewBag.surveys = database.surveyList().Find(smodel => smodel.id == identificador);
                database.closeConnection();
                database.openConnection();
                Survey surveyItem = database.surveyList().Find(smodel => smodel.id == identificador);
                database.closeConnection();
                database.openConnection();
                ViewBag.questions = database.questionList();
                database.closeConnection();

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Survey/Questions.cshtml
@model ElCaminoDeCostaRica.Models.Survey
@{ ViewBag.Title = "EncuestaPregunta";
    List<SelectListItem> rating = new List<SelectListItem>() { new
SelectListItem { Text = "1", Value= "1"},new SelectListItem { Text = "2", Value= "2"}, new SelectListItem { Text = "3", Value= "3"},
new SelectListItem { Text = "4", Value= "4"},new SelectListItem { Text = "5", Value= "5"},};
}
<html>
<head>
</head>

<body>

    @using (Html.BeginForm("Questions", "Survey", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.HiddenFor(model => model.id)
        @Html.HiddenFor(model => model.idService)
        @Html.HiddenFor(model => model.idCategory)
        <h1 align="center" style="color:black; font-family:Agrozza Demo">Encuesta</h1>
        <h2 align="center" style="color:black; font-family:Agrozza Demo">Califique las siguientes preguntas de la encuesta en una esacala del 1 al 5, en la que 1 es malo y 5 es excelente</h2>
        
        <div class="seccion_1" id="s1">

            @{ var count = 0;
                foreach (var question in ViewBag.questions)
                {
                    if (question.idSurvey == ViewBag.surveys.id)
                    {
                        <div class="text-center"> @question.question </div>
                        <div class="text-center">@Html.DropDownList("Calificacion" + count, rating, "-Sin selección - ", new { @class = "form - control" })</div>

                    }
                    count = +1;

                }

            }
            <div class="text-center" ;style="color:black">
                @Html.Label("Comentarios")
                @Html.TextBox("Comentarios")
            </div>
            <div class="text-center">
                <input type="submit" id="crear" class="btn btn-success btnCreate" value="Crear" />
            </div>

        </div>
    }
</body>
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Survey/addSurvey.cshtml
@model ElCaminoDeCostaRica.Models.Survey
@{
    List<SelectListItem> categories = new List<SelectListItem>();
    List<SelectListItem> services = new List<SelectListItem>();
    foreach (var category in ViewBag.Categories)
    {
        categories.Add(
        new SelectListItem { Text = Convert.ToString(category.name), Value = Convert.ToString(category.id) }
        );
    }

    foreach (var service in ViewBag.Services)
    {
        services.Add(
        new SelectListItem { Text = Convert.ToString(service.name), Value = Convert.ToString(service.id) }
        );
    }
}
<html>
<head>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>
<body>


    @if (ViewBag.Message != null)
    {
        if (ViewBag.Success)
        {
            <div class="alert-success">
                <h3> @ViewBag.Message </h3>
            </div>
        }
        else
        {
            <div class="alert-danger">
                <h3> @ViewBag.Message </h3>
            </div>
        }
    }

    @{

        using (Html.BeginForm("addSurvey", "Survey", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h1 class="formTitle">Crear encuesta</h1>


<<<<<<< HEAD
            <div class="form-style-9" ; style="color:black">
                @Html.LabelFor(model => model.version)
                @Html.TextBoxFor(model => model.version, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.version, "", new { @class = "text-danger" })
            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.LabelFor(model => model.day)
                @Html.TextBoxFor(model => model.day, new { @type = "date" })
                @Html.ValidationMessageFor(model => model.day, "", new { @class = "text-danger" })


            </div>
=======

            <section class="min-vh-100 " style=" font-size:x-large;">
                <div class="container py-5 h-100">
                    <div class="row d-flex justify-content-center align-items-center h-100">
                        <div class="col col-xl-10">
                            <div class="card" style="border-radius: 4rem; border-style: solid; border-color: #FAD586;">
                                <div class="row g-0 mb-7">

                                    <div class="col-md-6 col-lg-5 d-none d-md-block" ;>
                                        <img src="https://cdn-icons-png.flaticon.com/512/3593/3593663.png"
                                             alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem; margin: 8px 14px" />
                                    </div>

                                    <div class="col-md-6 col-lg-7 d-flex align-items-center" style="font-size:x-large">
                                        <div class="card-body p-4 p-lg-5 text-black">
                                            @Html.HiddenFor(model => model.id)

                                            <form>

                                                <h1 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px; color: #184D47">Añadir Encuesta</h1>

                                                <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.version)
                                                    @Html.TextBoxFor(model => model.version, new { @class = "form-control,form-control-lg" })
                                                    @Html.ValidationMessageFor(model => model.version, "", new { @class = "text-danger" })
                                                </div>



>>>>>>> Cesar

            <div class="form-style-9" ; style="color:black">
                @Html.LabelFor(model => model.idCategory)
                @Html.DropDownListFor(model => model.idCategory, categories, "-Sin selección - ", new { @class = "form - control" })
                @Html.ValidationMessageFor(model => model.idCategory, "", new { @class = "text-danger" })


            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.LabelFor(model => model.idService)
                @Html.DropDownListFor(model => model.idService, services, "-Sin selección - ", new { @class = "form - control" })
                @Html.ValidationMessageFor(model => model.idService, "", new { @class = "text-danger" })
            </div>
            @*<div id="newRow">
                    <button id="addRow" type="button" class="btn btn-info">Agregar Pregunta</button>
                </div>*@
            <div class="form-style-9" ; style="color:black">
                @Html.Label("Pregunta")
                @Html.TextBox("numero1", ViewBag.Num1 as string)
                @*@Html.ValidationMessageFor(String,"Debe ser un string", new { @class = "text-danger" })*@
            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.Label("Pregunta")
                @Html.TextBox("numero2", ViewBag.Num2 as string)
                @*@Html.ValidationMessageFor(String,"Debe ser un string", new { @class = "text-danger" })*@
            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.Label("Pregunta")
                @Html.TextBox("numero3", ViewBag.Num3 as string)
                @*@Html.ValidationMessageFor(String,"Debe ser un string", new { @class = "text-danger" })*@
            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.Label("Pregunta")
                @Html.TextBox("numero4", ViewBag.Num4 as string)
                @*@Html.ValidationMessageFor(String,"Debe ser un string", new { @class = "text-danger" })*@
            </div>

            <div class="form-style-9" ; style="color:black">
                @Html.Label("Pregunta")
                @Html.TextBox("numero5", ViewBag.Num5 as string)
                @*@Html.ValidationMessageFor(String,"Debe ser un string", new { @class = "text-danger" })*@
            </div>

            <div>
                <input type="submit" id="crear" class="btn btn-success btnCreate" value="Crear" />
            </div>

        }
        @*<script type="text/javascript">
                // agregar registro
                $("#addRow").click(function () {
                    var html = '';
                    html += '<div class="form-group" id="inputFormRow">';
                    html += '@Html.Label("Pregunta")';
                    html += '<input type="text" name="title[]" class="form-control m-input" placeholder="Ingrese pregunta" autocomplete="off">';
                    html += '<div class="input-group-append">';
                    html += '<button id="removeRow" type="button" class="btn btn-danger">Borrar</button>';
                    html += '</div>';
                    html += '</div>';


                    $('#newRow').append(html);
                });

                // borrar registro
                $(document).on('click', '#removeRow', function () {
                    $(this).closest('#inputFormRow').remove();
                });
<<<<<<< HEAD
=======
               <div class="form-outline mb-4">
                                                    @Html.LabelFor(model => model.day)
                                                    @Html.TextBoxFor(model => model.day, new { @type = "date" })
                                                    @Html.ValidationMessageFor(model => model.day, "", new { @class = "text-danger" })
                                                </div>
>>>>>>> Cesar

            </script>*@
    }
</body>
@section Scripts { @Scripts.Render("~/bundles/jqueryval") }
</html>

ElCaminoDeCostaRica/ElCaminoDeCostaRica/Views/Survey/surveyList.cshtml
@model ElCaminoDeCostaRica.Models.Survey
@{ ViewBag.Title = "Encuesta"; }
<html>
<head>
</head>

<body>

    <h1 align="center" style="color:black; font-family:Agrozza Demo">Lista de encuestas</h1>
<<<<<<< HEAD
=======
    
>>>>>>> Cesar
    <div class="seccion_1" id="s1">
        <table class="table">
            <tr>
                <th class="text-center">Id</th>
                <th class="text-center">Version</th>
<<<<<<< HEAD
                <th class="text-center">Dia</th>
=======
>>>>>>> Cesar
                <th class="text-center">Categoria</th>
                <th class="text-center">Servicio</th>
            </tr>
            <tbody>
<<<<<<< HEAD
                @foreach (var survey in ViewBag.surveys)
                {
                <tr>
                    <td class="text-center"> @survey.id </td>
                    <td class="text-center"> @survey.version </td>
                    <td class="text-center"> @survey.day </td>
                    @foreach (var category in ViewBag.cat)
                    {
                        if (category.id == survey.idCategory)
                        {
                            <td class="text-center"> @category.name </td>
                            break;
                        }
                    }
                    @foreach (var service in ViewBag.ser)
                    {
                        if (service.id == survey.idService)
                        {
                            <td class="text-center"> @service.name </td>
                            break;
                        }
                    }

                    <td>
                        @Html.ActionLink("Modificar", "surveyEdit", new { identificador = survey.id },
                                  new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere modificar esta encuesta ? ');" })
                    </td>
                    <td>
                        @Html.ActionLink("Borrar", "surveyDelete", new { identificador = survey.id },
                              new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere borrar esta encuesta? ');" })
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
=======
                @Html.HiddenFor(model => model.id)
                @Html.HiddenFor(model => model.idService)
                @Html.HiddenFor(model => model.idCategory)
                @foreach (var survey in ViewBag.surveys)
                {
                    <tr>
                        <td class="text-center"> @survey.id </td>
                        <td class="text-center"> @survey.version </td>
                        @foreach (var category in ViewBag.cat)
                        {
                            if (category.id == survey.idCategory)
                            {
                                <td class="text-center"> @category.name </td>
                                break;
                            }
                        }
                        @foreach (var service in ViewBag.ser)
                        {
                            if (service.id == survey.idService)
                            {
                                <td class="text-center"> @service.name </td>
                                break;
                            }
                        }

                        <td>
                            @Html.ActionLink("Modificar", "surveyEdit", new { identificador = survey.id },
                                      new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere modificar esta encuesta ? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Borrar", "surveyDelete", new { identificador = survey.id },
                                  new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere borrar esta encuesta? ');" })
                        </td>
                        <td>
                            @Html.ActionLink("Mostrar", "Questions", new { identificador = survey.id },
                                  new { @class = "btn btn alert-info", @onclick = "return confirm('¿Quiere mostras las preguntas? '};" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>

>>>>>>> Cesar
</body>
</html>